Worked on pg17 support WIP

diff --git a/timescaledb/rootfs/etc/s6-overlay/s6-rc.d/init-addon/run b/timescaledb/rootfs/etc/s6-overlay/s6-rc.d/init-addon/run
--- a/timescaledb/rootfs/etc/s6-overlay/s6-rc.d/init-addon/run
+++ b/timescaledb/rootfs/etc/s6-overlay/s6-rc.d/init-addon/run
@@ -199,6 +199,17 @@ else
 			exit 1
 		fi
 	fi
+
+	# Check if we need to upgrade from 16 to 17
+	if [[ $(< ${POSTGRES_DATA}/PG_VERSION) == "16" ]]; then
+		bashio::log.notice "A database upgrade is required from Postgres 17."
+		if upgradePostgreSQL 16 17; then
+			bashio::log.notice "Upgrade was succesful"
+		else
+			bashio::log.error "Upgrade was not succesful."
+			exit 1
+		fi
+	fi
 fi
 
 bashio::log.info "done"
